name: Setup

outputs:
  node-version:
    description: 'The installed node version.'
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: 'composite'
  steps:
    - id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - id: cache-node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{steps.setup-node.outputs.node-version}}-node_modules-${{hashFiles('package-lock.json')}}

    - run: npm ci --ignore-scripts --no-audit
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      shell: bash
