name: E2E Tests

inputs:
  env:
    type: choice
    description: Environment to run E2E in
    required: true
    options:
      - development
      - production

runs:
  using: 'composite'
  steps:
    - name: Define Playwright Version
      run: |
        PLAYWRIGHT_VERSION=$(cat package-lock.json | jq -r '.packages["node_modules/@playwright/test"].version')
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright Browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{steps.setup.outputs.node-version}}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{hashFiles('playwright.config.js')}}

    - name: Install Playwright Browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npm run e2e:setup:ci

    - name: Run E2E
      run: npm run e2e
      env:
        NODE_ENV: ${{ inputs.env }}

    - name: Upload E2E Test Report
      if: always() # is needed here to upload report even if e2e failed
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: playwright-report/
        retention-days: 30
