name: E2E Tests

inputs:
  env:
    type: choice
    description: Environment to run E2E in
    required: true
    options:
      - development
      - production

runs:
  using: 'composite'
  steps:
    - name: Define Playwright Version
      id: define-playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(npm run script scripts/get-package-version.ts --silent -- --package @playwright/test)
        echo "playwright-version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright Browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{steps.setup.outputs.node-version}}-playwright-${{ steps.define-playwright-version.outputs.playwright-version }}-${{hashFiles('playwright.config.js')}}

    - name: Install Playwright Browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npm run e2e:setup:ci
      shell: bash

    - name: Run E2E
      run: npm run e2e
      env:
        NODE_ENV: ${{ inputs.env }}
      shell: bash

    - name: Upload E2E Test Report
      if: always() # is needed here to upload report even if e2e failed
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: playwright-report/
        retention-days: 30
