name: E2E Tests

inputs:
  env:
    description: Environment to run E2E in
    required: true
  shard:
    description: Shard of E2E to run
    default: '1'
  total_shards:
    description: Total amount of shards E2E is split to
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Define Playwright Version
      id: define-playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(npm run script scripts/get-package-version.ts --silent -- --package @playwright/test)
        echo "playwright-version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright Browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{steps.setup.outputs.node-version}}-playwright-${{ steps.define-playwright-version.outputs.playwright-version }}-${{hashFiles('playwright.config.js')}}

    - name: Install Playwright Browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npm run e2e:setup:ci
      shell: bash

    - name: Run E2E
      run: npm run e2e -- --shard=${{ inputs.shard }}/${{ inputs.total_shards }}
      env:
        NODE_ENV: ${{ inputs.env }}
      shell: bash

    - name: Upload E2E Test Report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report-${{ inputs.shard }}_${{ inputs.total_shards }}
        path: playwright-report/
        retention-days: 30
