name: CI/CD

on:
  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run test:coverage

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 30

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run e2e:setup

      - run: npm run e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: false
    needs:
      - format
      - lint
      - test
      - e2e
      - build
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: vercel pull --environment=production --yes --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
