name: Dependencies check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm outdated
